name: Run Tests

permissions:
    contents: read

defaults:
    run:
        shell: bash

on:
    push:
        branches:
            - main
        paths:
            - .github/workflows/tests.yml
            - lune/**
            - src/**
            - .luaurc
            - tests/**

    pull_request:
    workflow_dispatch:
    merge_group:

jobs:
    Test:
        strategy:
            matrix:
                os:
                    [
                        { name: windows, version: windows-latest },
                        { name: ubuntu, version: ubuntu-latest },
                        { name: macos, version: macos-latest },
                        { name: macos-arm, version: macos-14 },
                    ]
        name: ${{matrix.os.name}}
        runs-on: ${{matrix.os.version}}

        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  # only checkout files which are needed for running tests
                  sparse-checkout: |
                      rokit.toml
                      .luaurc
                      lune/
                      src/
                      tests/
                  sparse-checkout-cone-mode: false

            - name: Setup Rokit
              uses: CompeyDev/setup-rokit@v0.1.2

            - name: Run Test Script
              run: lune run lune/tests.luau

            - name: Upload Artifact
              if: ${{ always() && github.repository == 'luau-ecs/signalis' }}
              uses: actions/upload-artifact@v4
              with:
                  name: tests-${{ matrix.os.name }}-${{ matrix.os.version }}
                  path: .test_artifact/
